unstable_features = true
edition = "2021"

tab_spaces = 4
hard_tabs = true
use_small_heuristics = "Max"
max_width = 120

control_brace_style = "AlwaysSameLine"
fn_single_line = true
chain_width = 100
fn_call_width = 100
imports_granularity = "Crate"
trailing_comma = "Vertical"
