unstable_features = true

tab_spaces = 4
hard_tabs = true
use_small_heuristics = "Max"
max_width = 120

control_brace_style = "ClosingNextLine"
fn_single_line = true
blank_lines_lower_bound = 1
chain_width = 100
fn_call_width = 100
imports_granularity = "Crate"
trailing_comma = "Never"
