name: rustfmt
on:
  pull_request:
  push:
    branches: [ $default-branch ]

jobs:
  format:
		name: Format Rust Sources
    runs-on: ubuntu-latest
    steps:
			- uses: actions/checkout@v3
			- name: Install Rust
				uses: ./.github/actions/actions-rs/toolchain
        with:
					toolchain: stable
					components: rustfmt
					override: true
			- name: Run 'rustfmt-check'
				uses: ./.github/actions/mbrobbel/rustfmt-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
