name: rustfmt
on:
  pull_request:
  push:
    branches: [ $default-branch ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
			- uses: ./.github/actions/actions-rs/toolchain
        with:
            toolchain: stable
            components: rustfmt
            override: true
			- uses: ./.github/actions/mbrobbel/rustfmt-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
